Z8T=/home/ceade/src/personal/github/z8t/z8t.pl

TESTS =
TESTS += 04-ringbuf-SPACE.z8t
TESTS += 04-ringbuf-READ.z8t
TESTS += 04-ringbuf-WRITE.z8t
TESTS += 04-ringbuf-READM.z8t
TESTS += 04-ringbuf-WRITEM.z8t

all: $(TESTS)
	$(Z8T) $(TESTS)
